Tomer/walet feture
TinyTeaTree/wearewarriors pull request #58
Opened 2024-12-03 00:42 UTC by tomerasraf

- Wallet visual is been created at runtime as the Hud navbar parent
- Player can now save his Wallet Balance for the next gamplay session.
- Added WalletBalance of 300 in the NewGame.Json for the sake of testing (we will change it later)

2024-12-03 20:23 UTC, ilia-gl commented on Assets/Scripts/Features/Wallet/WalletRecord.cs
> +        public int WalletBalance;
Can we call this Coins?

2024-12-03 20:27 UTC, ilia-gl requested changes
Solve Merge Conflicts and
Lets increase Migration Number in PlayerAccount, so that I will create a Wallet Record from NewJson

2024-12-04 07:30 UTC, tomerasraf commented on Assets/Scripts/Features/Wallet/WalletRecord.cs
> +        public int WalletBalance;
Yes we do

2024-12-04 08:55 UTC, ilia-gl approved these changes

2024-12-04 10:33 UTC, merged